name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build packages
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out target/wheels

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: target/wheels

      - name: Get app version
        id: package-version
        shell: bash
        run: |
          version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          echo "APP_VERSION=$version" >> $GITHUB_ENV

      - name: Create OS release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ matrix.os }}-v${{ env.APP_VERSION }}
          name: ${{ matrix.os }} release v${{ env.APP_VERSION }}
          artifacts: "/target/wheels/*.whl"
          bodyFile: "README.md"
